[FEATURE] #94218 - Selectable columns per table in record
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #173
Opened 2021-06-12 12:29 UTC by linawolf

references TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1395

2021-06-13 11:03 UTC, susannemoog requested changes

2021-06-13 11:03 UTC, susannemoog commented on Documentation/PageTsconfig/Mod.rst
> +    Enable the columns selector in the record list. This allows to compare
This sentence seems to be incomplete.

2021-06-13 11:03 UTC, susannemoog commented on Documentation/PageTsconfig/Mod.rst
> +   table gets hidden. If the column selctors have been disabled globally
selectors is missing an e

2021-06-26 09:28 UTC, linawolf commented on Documentation/PageTsconfig/Mod.rst
> +    Enable the columns selector in the record list. This allows to compare
I rephrased it

2021-07-02 16:30 UTC, susannemoog approved these changes

2021-07-03 07:27 UTC, merged