[FEATURE] Automatic inclusion of PageTsConfig of extensions
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #223
Opened 2022-03-20 08:23 UTC by linawolf

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96614-AutomaticInclusionOfPageTsConfigOfExtensions.html

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

2022-03-20 13:02 UTC, brotkrueml commented on Documentation/UsingSetting/PageTSconfig.rst
> +.. versionadded:: 10.2
I assume this should be 12.0, not 10.2?

2022-03-20 17:06 UTC, linawolf commented on Documentation/UsingSetting/PageTSconfig.rst
> +.. versionadded:: 10.2
Of course. fixed

2022-03-26 11:21 UTC, linawolf commented
@brotkrueml I resolved your comment, anything else or can the PR be merged like this?

2022-04-04 14:48 UTC, susannemoog requested changes

2022-04-04 14:48 UTC, susannemoog commented on Documentation/UsingSetting/PageTSconfig.rst
> +and extension is automatically loaded during build time.
an instead of and

2022-04-04 14:48 UTC, susannemoog commented on Documentation/UsingSetting/PageTSconfig.rst
> +Extensions supplying custom default Page TSconfig that should always be included,
do we write "page TSconfig" or "Page TSconfig" ?

2022-04-04 14:48 UTC, susannemoog commented on Documentation/UsingSetting/PageTSconfig.rst
> +TYPO3 11 and 12 by importing the content of this file with the API function
is it then imported twice in v12 // does this need a version condition surrounding it?

2022-04-08 07:00 UTC, susannemoog approved these changes

2022-04-23 16:43 UTC, merged