Introduce composer docs:generate
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #290
Opened 2022-09-03 10:29 UTC by linawolf

A command to locally generate the documentation. Idea taken from EXT:tea

2022-09-03 10:55 UTC, brotkrueml reviewed
I am not a fan of custom composer scripts which can also be added simply via a shell script (which you obviously do in the composer command; just run a sequence of shell commands).
So, I would add a shell script (also keep Windows in mind, I assume bash is there not available by default - apart from WSL2 - independently, if composer or not).

Don't know if this has a benefit, I see no issue in running two commands in sequence initially and then just run the second command only afterwards - as I recall the sh history quickly.

So, would leave the decision to others.

2022-09-03 11:02 UTC, linawolf commented
I would see this as an offer, none would force anyone to do it this way. I get questions from confused people all over again: How can I render the documentation? This way it would kind of documented in place. Just calling "composer" even lists you the script in the help section:
![image](https://user-images.githubusercontent.com/48202465/188267506-82806275-025e-4001-ac4f-c562c282a9c9.png)

2022-09-06 08:21 UTC, mabolek requested changes

2022-09-06 08:21 UTC, mabolek commented on CONTRIBUTING.md
> +* If you find something missing or something is wrong in this manual, you are welcome to write an issue describing the problem.
```suggestion
* If you find something missing or something is wrong in this manual, you are welcome to open an issue and describe the problem.
```

2022-09-06 08:21 UTC, mabolek commented on CONTRIBUTING.md
> +* If you can, please try to fix the problem yourself.
```suggestion
* Please feel free to submit a fix to the problem.
```

2022-09-06 13:20 UTC, linawolf commented
I think Gitpod is the better solution

2022-09-06 13:20 UTC, closed without merging