Update TceForm.rst
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #329
Opened 2023-01-12 14:52 UTC by michael-binder

I think this is a typo it should be 'maxitems' instead of 'max'

2023-01-12 16:06 UTC, brotkrueml commented on Documentation/PageTsconfig/TceForm.rst
> +      `TCEFORM.tt_content.header.config.maxitems`
You have to distinguish between maxItems (= select items) and max characters (in input field). Have you looked into the code=

2023-01-19 17:05 UTC, linawolf requested changes
I agree with @brotkrueml

2023-01-19 17:05 UTC, linawolf commented on Documentation/PageTsconfig/TceForm.rst
> +      `TCEFORM.tt_content.header.config.maxitems`
```suggestion
      `TCEFORM.tt_content.header.config.max`
```

I agree with @brotkrueml , thi must be left unchanges. input has the property 'max' , see above

2023-01-19 17:07 UTC, linawolf commented on Documentation/PageTsconfig/TceForm.rst
> +      `TCEFORM.tt_content.pi_flexform.my_ext_pi1.sDEF.myField.config.maxitems`
```suggestion
      `TCEFORM.tt_content.pi_flexform.my_ext_pi1.sDEF.myInputField.config.max`
```
I suggest we just make it more clear that this is an input field

2023-01-19 18:52 UTC, linawolf approved these changes

2023-01-19 18:52 UTC, merged