Breaking: #97135 - Removed support for module handling based on TBE_M…
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #462
Opened 2024-04-14 11:01 UTC by linawolf

…ODULES_EXT

References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/3 Releases: main, 12.4

2024-04-14 12:32 UTC, linawolf commented
the provided code for migration does not seem to work currently: https://forge.typo3.org/issues/103627. Should we make a note?

2024-04-14 16:59 UTC, brotkrueml requested changes

2024-04-14 16:59 UTC, brotkrueml commented on Documentation/PageTsconfig/Mod/WebTs.rst
> +..  todo: link to options.hideModules once it is documented
hideModules is documented, it is user TSconfig:
https://docs.typo3.org/m/typo3/reference-tsconfig/12.4/en-us/UserTsconfig/Options.html#hidemodules

2024-04-14 16:59 UTC, brotkrueml commented on Documentation/PageTsconfig/Mod/WebTs.rst
> +:file:`EXT:tstemplate/Configuration/Backend/Modules.php`.
Please use t3src for easy access.

2024-04-18 17:30 UTC, linawolf commented
Will be continued in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/463

2024-04-18 17:30 UTC, closed without merging