[TASK] Switch to confvals for rte
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #467
Opened 2024-04-14 13:44 UTC by linawolf

* use confvals
* correct indentation

releases: main, 12.4, 11.5

2024-04-14 16:48 UTC, brotkrueml requested changes

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +.. contents::
```suggestion
..  contents::
```

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :Default: false
```suggestion
    :Default: 0
```

This is page TSconfig, not PHP. I assume, "false" may be interpreted as true as it is a non-empty string.

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :Default: false
```suggestion
    :Default: 0
```

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :Default: false
```suggestion
    :Default: 0
```

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :Default: false
```suggestion
    :Default: 0
```

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~
```

2024-04-14 16:48 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
>         This configuration is similar in frontend TypoScript and Page TSconfig.
Indentation missing.

2024-04-15 12:42 UTC, linawolf commented on Documentation/PageTsconfig/Rte.rst
>         and :code:`htmlSpecialChars` are *not* observed. They are preset internally.
```suggestion
        This configuration is similar in frontend TypoScript and Page TSconfig.
        This is why single properties can be looked up in the TypoScript reference.

        Also note the :ref:`HTMLparser <t3tsref:htmlparser>` options :code:`keepNonMatchedTags`
        and :code:`htmlSpecialChars` are *not* observed. They are preset internally.
```

2024-04-16 17:16 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-allowTags:
```suggestion
    :name: rte-proc-allowTags
```

2024-04-16 17:17 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-relattribute-enabled:
```suggestion
    :name: rte-buttons-link-relattribute-enabled
```

2024-04-16 17:17 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-properties-class-allowedclasses:
```suggestion
    :name: rte-buttons-link-properties-class-allowedclasses
```

2024-04-16 17:18 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-properties-class-required:
```suggestion
    :name: rte-buttons-link-properties-class-required
```

2024-04-16 17:18 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-type-properties-class-required:
```suggestion
    :name: rte-buttons-link-type-properties-class-required
```

2024-04-16 17:18 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-properties-target-default:
```suggestion
    :name: rte-buttons-link-properties-target-default
```

2024-04-16 17:19 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-buttons-link-type-properties-target-default:
```suggestion
    :name: rte-buttons-link-type-properties-target-default
```

2024-04-16 17:19 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-config-contentsLanguageDirection:
```suggestion
    :name: rte-config-contentsLanguageDirection
```

2024-04-16 17:20 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-allowedClasses:
```suggestion
    :name: rte-proc-allowedClasses
```

2024-04-16 17:21 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-denyTags:
```suggestion
    :name: rte-proc-denyTags
```

2024-04-16 17:21 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-entryHTMLparser_db:
```suggestion
    :name: rte-proc-entryHTMLparser_db
```

2024-04-16 17:22 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-entryHTMLparser_rte:
```suggestion
    :name: rte-proc-entryHTMLparser_rte
```

2024-04-16 17:22 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-exitHTMLparser_db:
```suggestion
    :name: rte-proc-exitHTMLparser_db
```

2024-04-16 17:22 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-exitHTMLparser_rte:
```suggestion
    :name: rte-proc-exitHTMLparser_rte
```

2024-04-16 17:23 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-HTMLparser_db:
```suggestion
    :name: rte-proc-HTMLparser_db
```

2024-04-16 17:23 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-HTMLparser_rte:
```suggestion
    :name: rte-proc-HTMLparser_rte
```

2024-04-16 17:24 UTC, brotkrueml commented on Documentation/PageTsconfig/Rte.rst
> +    :name: rte-proc-overruleMode:
```suggestion
    :name: rte-proc-overruleMode
```

2024-04-16 17:24 UTC, brotkrueml approved these changes

2024-04-17 04:24 UTC, merged