[TASK] Improve Condition page
TYPO3-Documentation/TYPO3CMS-Reference-TSconfig pull request #490
Opened 2024-04-19 06:51 UTC by linawolf

- use confvals
- correct indentation
- unify and improve examples (always end a condition, we are in TSconfig here)
- give titles to examples
- add todos where examples seemed strange to me

releases: main, 12.4, 11.5

2024-04-19 12:21 UTC, brotkrueml requested changes
We use capitalized "[END]" in TypoScript conditions:
https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Conditions/Index.html

Is this does not really matter we should use also capitalized "[END]" here for constistency reasons.

Additionally, this PR does many things, needed approx. 30 minutes for a review. Consider breaking them up into separate PRs in the future. I assume, will need the next time for this also 30 minutes :-(

2024-04-19 12:21 UTC, brotkrueml commented on Documentation/UsingSetting/Conditions.rst
> +    array of arrays with uid and pid. Only available in page TSconfig, not
```suggestion
    An array of arrays with uid and pid. Only available in page TSconfig, not
```

2024-04-19 12:21 UTC, brotkrueml commented on Documentation/UsingSetting/Conditions.rst
> +    An array with UIDs of the rootline. Only available in page TSconfig, not
```suggestion
    An array with UIDs of the root line. Only available in page TSconfig, not
```

2024-04-19 13:41 UTC, linawolf commented on Documentation/UsingSetting/Conditions.rst
> +Example: Condition applies only in a certain workspace
Here we can use any workspace ID while the example bellow checks if we are in the life workspace. So I would keep the text as it currently is

2024-04-19 13:46 UTC, linawolf commented
I changed [end] into [END] to be consistent, however [end] also works

2024-04-19 14:23 UTC, brotkrueml commented
> I changed [end] into [END] to be consistent, however [end] also works

Yup, both work, also [global] and [GLOBAL], but we should be consistent throughout the docs.

2024-04-19 14:23 UTC, brotkrueml commented on Documentation/UsingSetting/Conditions.rst
> +Example: Condition applies only in a certain workspace
Then maybe change the example to an arbitrary number (42).

2024-04-19 14:24 UTC, linawolf commented
So are there any other open issues?

2024-04-20 14:17 UTC, brotkrueml approved these changes

2024-04-20 17:57 UTC, merged